const questions = [
  "I pride myself on having a large vocabulary.",
  "Using numbers and numerical symbols is easy for me.",
  "Music is very important to me in daily life.",
  "I always know where I am in relation to my home.",
  "I consider myself an athlete.",
  "I feel like people of all ages like me.",
  "I often look for weaknesses in myself that I see in others.",
  "The world of plants and animals is important to me.",
  "I enjoy learning new words and do so easily.",
  "I often develop equations to describe relationships and/or to explain my observations.",
  "I have wide and varied musical interests including both classical and contemporary.",
  "I do not get lost easily and can orient myself with either maps or landmarks.",
  "I feel really good about being physically fit.",
  "I like to be with all different types of people.",
  "I often think about the influence I have on others.",
  "I enjoy my pets.",
  "I love to read and do so daily.",
  "I often see mathematical ratios in the world around me.",
  "I have a very good sense of pitch, tempo, and rhythm.",
  "Knowing directions is easy for me.",
  "I have good balance and eye-hand coordination and enjoy sports which use a ball.",
  "I respond to all people enthusiastically, free of bias or prejudice.",
  "I believe that I am responsible for my actions and who I am.",
  "I like learning about nature.",
  "I enjoy hearing challenging lectures.",
  "Math has always been one of my favorite classes.",
  "My music education began when I was younger and still continues today.",
  "I have the ability to represent what I see by drawing or painting.",
  "My outstanding coordination and balance let me excel in high-speed activities.",
  "I enjoy new or unique social situations.",
  "I try not to waste my time on trivial pursuits.",
  "I enjoy caring for my house plants.",
  "I like to keep a daily journal of my daily experiences.",
  "I like to think about numerical issues and examine statistics.",
  "I am good at playing an instrument and singing.",
  "My ability to draw is recognized and complimented by others.",
  "I like being outdoors, enjoy the change in seasons, and look forward to different physical activities each season.",
  "I enjoy complimenting others when they have done well.",
  "I often think about the problems in my community, state, and/or world and what I can do to help rectify any of them.",
  "I enjoy hunting and fishing.",
  "I read and enjoy poetry and occasionally write my own.",
  "I seem to understand things around me through a mathematical sense.",
  "I can remember the tune of a song when asked.",
  "I can easily duplicate color, form, shading, and texture in my work.",
  "I like the excitement of personal and team competition.",
  "I am quick to sense in others dishonesty and desire to control me.",
  "I am always totally honest with myself.",
  "I enjoy hiking in natural places.",
  "I talk a lot and enjoy telling stories.",
  "I enjoy doing puzzles.",
  "I take pride in my musical accomplishments.",
  "Seeing things in three dimensions is easy for me, and I like to make things in three dimensions.",
  "I like to move around a lot.",
  "I feel safe when I am with strangers.",
  "I enjoy being alone and thinking about my life and myself.",
  "I look forward to visiting the zoo.",
  "I am a private person and I like my private inner world.",
  "I like to move, tap or fidget when sitting.",
  "I work best in an organized work area.",
  "I have a collection (e.g. shells, mugs, rocks, hockey cards).",
  "I work best through interaction with people.",
  "I like puns and other wordplay.",
  "I play music in my head.",
  "I understand colour combinations and what colours work well together.",
  "I feel comfortable and get positive reinforcement when dealing with language and words.",
  "I enjoy solving jigsaw, maze and/or other visual puzzles.",
  "I notice similarities and differences in trees, flowers and other things in nature. ",
  "I make up a rhyme to remember something.",
  "I have a few close friends.",
  "I enjoy team sports rather than individual sports.",
  "I enjoy math and/or science.",
  "I participate in extreme sports (e.g. sea kayaking, snowboarding, mountain biking).",
  "I enjoy completing crosswords and other word games like Scrabble.",
  "Being around people energizes me.",
  "It is easy for me to follow the beat of music.",
  "I keep a \"things to do\" list.",
  "I have strong opinions about controversial issues.",
  "I am actively involved in protecting the environment.",
  "I read charts and maps easily.",
  "I am curious as to how things feel and I tend to touch objects and examine the texture.",
  "I enjoy playing brainteasers and games that involve logical thinking such as Jeopardy and Clue.",
  "I am well coordinated.",
  "I work best when the activity is self-paced.",
  "I remember things exactly as they are said to me.",
  "I like setting songs and poems to music.",
  "I enjoy digging for and discovering artifacts and unusual items.",
  "I prefer group activities rather than ones I do alone.",
  "I have a good sense of direction.",
  "I like to take part in debates and/or discussions.",
  "I keep time when music is playing.",
  "I like to watch the scenes and activities in movies.",
  "I like to ask \"why\" questions and seek clarification of issues and concerns.",
  "I like working with my hands.",
  "I enjoy learning about different cultures.",
  "I am not easily influenced by other people.",
  "I prefer to be outdoors rather than indoors.",
  "I am good at estimating.",
  "I work best in a co-operative group where I can discuss issues with others.",
  "I understand that I am responsible for my own behavior.",
  "I remember things best by seeing them."
];
export default questions;
